// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_STATEVECTOR_STATE_VECTOR_H_
#define FLATBUFFERS_GENERATED_STATEVECTOR_STATE_VECTOR_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

namespace state_vector {

struct Vec3;

struct Quaternion;

struct GeneralState;
struct GeneralStateBuilder;

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Vec3 FLATBUFFERS_FINAL_CLASS {
 private:
  float x_;
  float y_;
  float z_;

 public:
  Vec3()
      : x_(0),
        y_(0),
        z_(0) {
  }
  Vec3(float _x, float _y, float _z)
      : x_(::flatbuffers::EndianScalar(_x)),
        y_(::flatbuffers::EndianScalar(_y)),
        z_(::flatbuffers::EndianScalar(_z)) {
  }
  float x() const {
    return ::flatbuffers::EndianScalar(x_);
  }
  float y() const {
    return ::flatbuffers::EndianScalar(y_);
  }
  float z() const {
    return ::flatbuffers::EndianScalar(z_);
  }
};
FLATBUFFERS_STRUCT_END(Vec3, 12);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Quaternion FLATBUFFERS_FINAL_CLASS {
 private:
  float x_;
  float y_;
  float z_;
  float w_;

 public:
  Quaternion()
      : x_(0),
        y_(0),
        z_(0),
        w_(0) {
  }
  Quaternion(float _x, float _y, float _z, float _w)
      : x_(::flatbuffers::EndianScalar(_x)),
        y_(::flatbuffers::EndianScalar(_y)),
        z_(::flatbuffers::EndianScalar(_z)),
        w_(::flatbuffers::EndianScalar(_w)) {
  }
  float x() const {
    return ::flatbuffers::EndianScalar(x_);
  }
  float y() const {
    return ::flatbuffers::EndianScalar(y_);
  }
  float z() const {
    return ::flatbuffers::EndianScalar(z_);
  }
  float w() const {
    return ::flatbuffers::EndianScalar(w_);
  }
};
FLATBUFFERS_STRUCT_END(Quaternion, 16);

struct GeneralState FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef GeneralStateBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_POSITION = 4,
    VT_VELOCITY = 6,
    VT_ORIENTATION = 8,
    VT_ATM_DENSITY = 10,
    VT_ATM_PRESSURE = 12,
    VT_ATM_TEMPERATURE = 14,
    VT_GRAVITY = 16,
    VT_TIME = 18,
    VT_UTC = 20,
    VT_WIND_SPEED = 22
  };
  const state_vector::Vec3 *position() const {
    return GetStruct<const state_vector::Vec3 *>(VT_POSITION);
  }
  const state_vector::Vec3 *velocity() const {
    return GetStruct<const state_vector::Vec3 *>(VT_VELOCITY);
  }
  const state_vector::Quaternion *orientation() const {
    return GetStruct<const state_vector::Quaternion *>(VT_ORIENTATION);
  }
  float atm_density() const {
    return GetField<float>(VT_ATM_DENSITY, 0.0f);
  }
  float atm_pressure() const {
    return GetField<float>(VT_ATM_PRESSURE, 0.0f);
  }
  float atm_temperature() const {
    return GetField<float>(VT_ATM_TEMPERATURE, 0.0f);
  }
  const state_vector::Vec3 *gravity() const {
    return GetStruct<const state_vector::Vec3 *>(VT_GRAVITY);
  }
  float Time() const {
    return GetField<float>(VT_TIME, 0.0f);
  }
  float UTC() const {
    return GetField<float>(VT_UTC, 0.0f);
  }
  const state_vector::Vec3 *wind_speed() const {
    return GetStruct<const state_vector::Vec3 *>(VT_WIND_SPEED);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<state_vector::Vec3>(verifier, VT_POSITION, 4) &&
           VerifyField<state_vector::Vec3>(verifier, VT_VELOCITY, 4) &&
           VerifyField<state_vector::Quaternion>(verifier, VT_ORIENTATION, 4) &&
           VerifyField<float>(verifier, VT_ATM_DENSITY, 4) &&
           VerifyField<float>(verifier, VT_ATM_PRESSURE, 4) &&
           VerifyField<float>(verifier, VT_ATM_TEMPERATURE, 4) &&
           VerifyField<state_vector::Vec3>(verifier, VT_GRAVITY, 4) &&
           VerifyField<float>(verifier, VT_TIME, 4) &&
           VerifyField<float>(verifier, VT_UTC, 4) &&
           VerifyField<state_vector::Vec3>(verifier, VT_WIND_SPEED, 4) &&
           verifier.EndTable();
  }
};

struct GeneralStateBuilder {
  typedef GeneralState Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_position(const state_vector::Vec3 *position) {
    fbb_.AddStruct(GeneralState::VT_POSITION, position);
  }
  void add_velocity(const state_vector::Vec3 *velocity) {
    fbb_.AddStruct(GeneralState::VT_VELOCITY, velocity);
  }
  void add_orientation(const state_vector::Quaternion *orientation) {
    fbb_.AddStruct(GeneralState::VT_ORIENTATION, orientation);
  }
  void add_atm_density(float atm_density) {
    fbb_.AddElement<float>(GeneralState::VT_ATM_DENSITY, atm_density, 0.0f);
  }
  void add_atm_pressure(float atm_pressure) {
    fbb_.AddElement<float>(GeneralState::VT_ATM_PRESSURE, atm_pressure, 0.0f);
  }
  void add_atm_temperature(float atm_temperature) {
    fbb_.AddElement<float>(GeneralState::VT_ATM_TEMPERATURE, atm_temperature, 0.0f);
  }
  void add_gravity(const state_vector::Vec3 *gravity) {
    fbb_.AddStruct(GeneralState::VT_GRAVITY, gravity);
  }
  void add_Time(float Time) {
    fbb_.AddElement<float>(GeneralState::VT_TIME, Time, 0.0f);
  }
  void add_UTC(float UTC) {
    fbb_.AddElement<float>(GeneralState::VT_UTC, UTC, 0.0f);
  }
  void add_wind_speed(const state_vector::Vec3 *wind_speed) {
    fbb_.AddStruct(GeneralState::VT_WIND_SPEED, wind_speed);
  }
  explicit GeneralStateBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<GeneralState> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<GeneralState>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<GeneralState> CreateGeneralState(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const state_vector::Vec3 *position = nullptr,
    const state_vector::Vec3 *velocity = nullptr,
    const state_vector::Quaternion *orientation = nullptr,
    float atm_density = 0.0f,
    float atm_pressure = 0.0f,
    float atm_temperature = 0.0f,
    const state_vector::Vec3 *gravity = nullptr,
    float Time = 0.0f,
    float UTC = 0.0f,
    const state_vector::Vec3 *wind_speed = nullptr) {
  GeneralStateBuilder builder_(_fbb);
  builder_.add_wind_speed(wind_speed);
  builder_.add_UTC(UTC);
  builder_.add_Time(Time);
  builder_.add_gravity(gravity);
  builder_.add_atm_temperature(atm_temperature);
  builder_.add_atm_pressure(atm_pressure);
  builder_.add_atm_density(atm_density);
  builder_.add_orientation(orientation);
  builder_.add_velocity(velocity);
  builder_.add_position(position);
  return builder_.Finish();
}

inline const state_vector::GeneralState *GetGeneralState(const void *buf) {
  return ::flatbuffers::GetRoot<state_vector::GeneralState>(buf);
}

inline const state_vector::GeneralState *GetSizePrefixedGeneralState(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<state_vector::GeneralState>(buf);
}

inline bool VerifyGeneralStateBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<state_vector::GeneralState>(nullptr);
}

inline bool VerifySizePrefixedGeneralStateBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<state_vector::GeneralState>(nullptr);
}

inline void FinishGeneralStateBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<state_vector::GeneralState> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedGeneralStateBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<state_vector::GeneralState> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace state_vector

#endif  // FLATBUFFERS_GENERATED_STATEVECTOR_STATE_VECTOR_H_
